---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-go-app
spec:
  selector:
    matchLabels:
      app: first-go-app
  replicas: 4
  template:
    metadata:
      labels:
        app: first-go-app
    spec:
      containers:
        - name: azure-go-app
          image: "azconfdemoacr01.azurecr.io/golangimages/first-goapp:latest"
          env:
            - name: "PORT"
              value: "3000"
          ports:
            - name: go-app-port
              containerPort: 3000
