---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-go-app
spec:
  selector:
    matchLabels:
      app: first-go-app
  replicas: 4
  template:
    metadata:
      labels:
        app: first-go-app
    spec:
      containers:
        - name: azure-go-app
          image: "<img url>"
          envFrom:
            - secretRef:
                name: az-sp
          env:
            - name: "PORT"
              value: "8000"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: go-app-port
              containerPort: 8000
